title: Yutian's Blog
baseurl: "/blog"
description: A place for me to Learn, Create and Share
author: Yutian Chen
avatar: /avatar.jpg
email: yutianch@andrew.cmu.edu
location: Pittsburgh, PA
# disqus: yutian-blog

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
markdown: kramdown
highlighter: rouge

excerpt_separator: <!--more-->
paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
# twitter:
#   username: ngzhio
#   card: summary
logo: logo.png
social:
  name: Yutian Chen
  links:
    # - https://twitter.com/ngzhio
    # - https://www.facebook.com/ngzhio
    - https://github.com/MarkChenYutian
# google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
