title: Yutian's Blog
baseurl: ""
description: A place for me to Learn, Create and Share
author: Yutian Chen
avatar: /avatar.jpg
email: yutianch@andrew.cmu.edu
location: Pittsburgh, PA
# disqus: yutian-blog

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
markdown: kramdown
highlighter: rouge

excerpt_separator: <!--more-->
paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - README.md
  - jekyll-theme-hamilton.gemspec
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

logo: logo.png
social:
  name: Yutian Chen
  links:
    - https://github.com/MarkChenYutian
lang: en
